# Generated by Django 4.0.6 on 2023-02-16 00:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_ordered', models.BooleanField(default=False, verbose_name='is ordered')),
                ('total', models.IntegerField(blank=True, null=True, verbose_name='total')),
            ],
            options={
                'verbose_name': 'عربة',
                'verbose_name_plural': 'العربات',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='اسم الفئة')),
                ('image', models.ImageField(upload_to='', verbose_name='صورة')),
            ],
            options={
                'verbose_name': 'فئة',
                'verbose_name_plural': 'الفئات',
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم اللون')),
                ('color_code', models.CharField(help_text='ادخل اللون مثل: OxFF45B9EE', max_length=12, verbose_name='رمز اللون (HEX)')),
            ],
            options={
                'verbose_name': 'لون',
                'verbose_name_plural': 'الالوان',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('is_ordered', models.BooleanField(default=False, verbose_name='is ordered')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='اسم المنتج')),
                ('banner', models.ImageField(upload_to='banners/', verbose_name='الصورة')),
                ('description', models.TextField(blank=True, verbose_name='الوصف')),
                ('price', models.IntegerField(verbose_name='السعر')),
                ('stock', models.IntegerField(verbose_name='عدد القطع بالمخزن')),
                ('is_available', models.BooleanField(default=True, verbose_name='متوفر؟')),
                ('show_hide', models.BooleanField(default=True, verbose_name='اظهر هذا المنتج')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الانشاء')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'منتج',
                'verbose_name_plural': 'المنتجات',
                'ordering': ['-updated'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='صورة')),
            ],
            options={
                'verbose_name': 'صورة منتج',
                'verbose_name_plural': 'صور المنتج',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fav', models.BooleanField(default=False, verbose_name='is favorite')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs', to='MyStore.product', verbose_name='product')),
            ],
        ),
    ]
