# Generated by Django 4.0.6 on 2022-12-23 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='color_code',
            field=models.CharField(help_text='ادخل اللون مثل: OxFF45B9EE', max_length=12, verbose_name='رمز اللون (HEX)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='banner',
            field=models.ImageField(upload_to='banners/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MyStore.category', verbose_name='الفئة'),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.ManyToManyField(related_name='products', to='MyStore.color', verbose_name='الالوان'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='MyStore.product'),
        ),
    ]
