# Generated by Django 4.0.6 on 2023-04-07 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyStore', '0003_colorlogo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colorlogo',
            options={'verbose_name': ' لون الثيم واللوكو', 'verbose_name_plural': ' لون الثيم واللوكو'},
        ),
    ]
