# Generated by Django 4.0.6 on 2023-02-08 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('MyStore', '0003_item_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_fav', models.BooleanField(default=False, verbose_name='is favorite')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs', to='MyStore.product', verbose_name='product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favs', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
